couchbase/couchbase-ruby-client

lib/couchbase/config_profiles.rb, lib/couchbase/options.rb, test/config_profiles_test.rb
Adding support for configuration profiles ([RFC-0074](https://github.com/couchbaselabs/sdk-rfcs/blob/master/rfc/0074-config-profiles.md), [RCBC-388](https://issues.couchbase.com/browse/RCBC-388))
Provides the ability to apply one of the known profiles, as well as register custom profiles. A development profile has been implemented (Profile name: `"wan_development"`). 
**Applying the development profile:**
```ruby
opts = Couchbase::Cluster::ClusterOptions.new
opts.apply_profile("wan_development")
```
A custom profile is created by extending the `Profile` class and overwriting its `apply()` method. The profile should be registered before it can be applied.
**Creating a new custom profile:**
```ruby
class CustomProfile < Couchbase::ConfigProfiles::Profile
def apply(options) …
```
=> RCBC-388: Add Configuration Profiles

ext/couchbase.cxx, lib/couchbase/management/user_manager.rb, test/user_manager_test.rb
**Changes:**
- Updated core
- Added `change_password` function in `Management::UserManager` for changing the password of the current user
- Added a relevant test in `UserManagerTest`
=> RCBC-378: Implement change_password

test/user_manager_test.rb
This should fix the failing test on jenkins. The sleep needed seems to vary between clusters (Running locally on docker, it was fine for one cluster without a sleep, but another one needed some delay after changing the password or upserting a user, 0.1s was sufficient)
=> Add sleep after upserting user and changing password in change_password test

lib/couchbase/protostellar/binary_collection.rb, lib/couchbase/protostellar/collection.rb, lib/couchbase/protostellar/generated/admin/bucket.v1_services_pb.rb, lib/couchbase/protostellar/generated/admin/collection.v1_pb.rb, lib/couchbase/protostellar/generated/admin/collection.v1_services_pb.rb, lib/couchbase/protostellar/generated/analytics.v1_services_pb.rb, lib/couchbase/protostellar/generated/internal/health.v1_services_pb.rb, lib/couchbase/protostellar/generated/internal/hooks.v1_services_pb.rb, lib/couchbase/protostellar/generated/kv.v1_pb.rb, lib/couchbase/protostellar/generated/kv.v1_services_pb.rb, lib/couchbase/protostellar/generated/query.v1_services_pb.rb, lib/couchbase/protostellar/generated/routing.v1_services_pb.rb, lib/couchbase/protostellar/generated/search.v1_services_pb.rb, lib/couchbase/protostellar/generated/transactions.v1_services_pb.rb, lib/couchbase/protostellar/generated/view.v1_services_pb.rb, lib/couchbase/protostellar/request_generator/kv.rb, lib/couchbase/protostellar/response_converter/kv.rb, sig/couchbase/protostellar/binary_collection.rbs, sig/couchbase/protostellar/collection.rbs, sig/couchbase/protostellar/request_generator/kv.rbs, sig/couchbase/protostellar/response_converter/kv.rbs, spec/couchbase/protostellar/binary_collection_spec.rb, spec/couchbase/protostellar/collection_spec.rb
* Added `Protostellar::BinaryCollection` with `append`, `prepend`, `increment`, `decrement` and relevant tests
Some other small changes:
* Changed `expiry` to `expiry_time` in KV requests because of the breaking changes in Protostellar (will need to revisit expiry to make it fully compatible with the new Protostellar definition)
* Setting content type to `BINARY` in requests when the transcoder is `nil`
=> RCBC-409: Implement binary KV operations

lib/couchbase/protostellar/binary_collection.rb, lib/couchbase/protostellar/cluster.rb, lib/couchbase/protostellar/collection.rb, lib/couchbase/protostellar/error.rb, lib/couchbase/protostellar/error_handling.rb, lib/couchbase/protostellar/generated/kv/v1/kv_pb.rb, lib/couchbase/protostellar/management/collection_manager.rb, lib/couchbase/protostellar/request.rb, lib/couchbase/protostellar/request_generator/kv.rb, lib/couchbase/protostellar/request_generator/query.rb, lib/couchbase/protostellar/response_converter/admin/collection.rb, lib/couchbase/protostellar/response_converter/kv.rb, lib/couchbase/protostellar/response_converter/query.rb, lib/couchbase/protostellar/retry/strategies/best_effort.rb, lib/couchbase/protostellar/scope.rb, sig/couchbase/protostellar/collection.rbs, sig/couchbase/protostellar/request.rbs, sig/couchbase/protostellar/request_generator/kv.rbs, sig/couchbase/protostellar/request_generator/query.rbs, sig/couchbase/protostellar/response_converter/admin/collection.rbs, sig/couchbase/protostellar/response_converter/kv.rbs, sig/couchbase/protostellar/response_converter/query.rbs, spec/couchbase/protostellar/collection_spec.rb
* Updated protostellar
* Expiry now makes use of the ability to specify either `expiry_secs` or `expiry_time`
* Some small bug fixes in retry/error handling
* Tidied up the methods in the response converters
* Replaced `content_type` with the new `content_flags` attribute in protostellar requests
* Fixed issue in the `#get_and_lock` test
=> Update protostellar & bug fixes

lib/couchbase/search_options.rb, test/search_test.rb
* Added `to_h` methods that have the logic that used to be in `to_json` (This is helpful for the protostellar SDK). The `to_json` method is now defined in the base class and just converts to JSON what is returned by `to_h`
* Removed the `operator` attribute from all search queries apart from `MatchQuery` as per the RFC
* Removed some other attributes that are not in the spec (e.g. in `MatchAllQuery`)
* Allow `prefix_length` without `fuzziness` in `MatchQuery`
* Fixed `DocIdQuery` (`doc_id` had to be renamed to `id`, otherwise the server returns an error) + added a test for this
=> RCBC-422: Remove extra attributes, fix bugs and add to_h

lib/couchbase/raw_binary_transcoder.rb, lib/couchbase/raw_json_transcoder.rb, lib/couchbase/raw_string_transcoder.rb, lib/couchbase/transcoder_flags.rb, test/json_transcoder_test.rb, test/raw_binary_transcoder_test.rb, test/raw_json_transcoder_test.rb, test/raw_string_transcoder_test.rb
* Added `RawJsonTranscoder`, `RawBinaryTranscoder` and `RawStringTranscoder`
* Added the `TranscoderFlags` to handle the encoding and decoding of flags
* Added tests for the `JsonTranscoder` and the newly added transcoders
* Added check to the `JsonTranscoder` to ensure that if string data is provided it has a valid encoding
* Added check to the `JsonTranscoder` to ensure that the flag has the format set as json
=> RCBC-420: Support RawJson, RawBinary and RawString transcoders & check flag when decoding

lib/couchbase/protostellar/client.rb, lib/couchbase/protostellar/cluster.rb, lib/couchbase/protostellar/connect_options.rb, lib/couchbase/protostellar/request.rb, lib/couchbase/protostellar/request_generator/admin/bucket.rb, lib/couchbase/protostellar/request_generator/admin/collection.rb, lib/couchbase/protostellar/request_generator/kv.rb, lib/couchbase/protostellar/request_generator/query.rb, lib/couchbase/protostellar/request_generator/search.rb, lib/couchbase/protostellar/timeouts.rb, sig/couchbase/protostellar/client.rbs, sig/couchbase/protostellar/connect_options.rbs, sig/couchbase/protostellar/request.rbs, sig/couchbase/protostellar/request_generator/admin/bucket.rbs, sig/couchbase/protostellar/request_generator/admin/collection.rbs, sig/couchbase/protostellar/request_generator/kv.rbs, sig/couchbase/protostellar/request_generator/query.rbs, sig/couchbase/protostellar/request_generator/search.rbs, sig/couchbase/protostellar/timeouts.rbs, spec/couchbase/protostellar/timeouts_spec.rb
* Added `Timeouts` class which holds the global timeouts (either the ones that are defined in the cluster options or the defaults if they are not set in the cluster options)
* The timeouts are passed on to the `Client` which fills in the timeout in the request before sending it with the default value if it's not already defined
* Added some unit tests for the `Timeouts` class
=> RCBC-426: Use the default timeouts set in the cluster options

lib/couchbase/protostellar/client.rb, lib/couchbase/protostellar/error_handling.rb, spec/support/shared_examples/collection_subdoc.rb
* Handling more types of GRPC status
* Tidy up the stub variables in `Protostellar::Client`
* Use the error message from the GRPC status
=> RCBC-437: Update error mappings to include any recent additions

lib/couchbase/protostellar/error_handling.rb, lib/couchbase/protostellar/management/collection_query_index_manager.rb, lib/couchbase/protostellar/request_generator/admin/query.rb, lib/couchbase/protostellar/response_converter/admin/query.rb
* Added `ScopeExists`, `BucketExists` & `CollectionExists` in error map
* Fixed `NameError` when trying to raise an `Error::InvalidArgument`
* Add `scope_name` and `collection_name` from the options to query index management requests
* Include bucket/scope/collection names in result for `get_all_indexes`
=> Bug fixes & small improvements

lib/couchbase/utils/time.rb, test/utils_time_test.rb
For example, all timeout arguments are durations in milliseconds
=> RCBC-441: interpret Integer as milliseconds in duration context

ext/couchbase.cxx
Protocol logger could be enabled like this:
Couchbase::Backend.enable_protocol_logger_to_save_network_traffic_to_file("/tmp/cb.log")
Then all the logs will be recorded (and rotated automatically):
$ ls -1 /tmp/cb.log*
/tmp/cb.log.000000.txt
$ head /tmp/cb.log.000000.txt
[2023-07-26 13:59:17.107] [618461,0] [info] 0ms, ---------- Opening logfile: /tmp/cb.log.000000.txt
[2023-07-26 13:59:40.453] [618461,619134] [trace] 23345ms, [MCBP, OUT] host="127.0.0.1", port=12000, buffer_size=220
0000: 80 1f 00 a4 00 00 00 00 00 00 00 c4 00 00 00 01 00 00 00 00 00 00 00 00 7b 22 61 22 3a 22 63 78  ........................{"a":"cx
0020: 78 2f 31 2e 30 2e 30 2f 33 34 31 65 30 31 62 3b 4c 69 6e 75 78 2f 78 38 36 5f 36 34 3b 72 75 62  x/1.0.0/341e01b;Linux/x86_64;rub
0040: 79 5f 73 64 6b 2f 62 35 33 35 39 …
=> update core to 1.0.0-dp.7

ext/couchbase.cxx, lib/couchbase/collection.rb, lib/couchbase/collection_options.rb, lib/couchbase/options.rb, test/subdoc_test.rb, test/test_helper.rb
* Add support for `Collection#lookup_in_any_replica` and `Collection#lookup_in_all_replicas`
* Changed the wrapper code of `lookup_in` to use the Core API instead of the Public C++ API
* Added relevant options and result classes (`Options::LookupInAnyReplica`, `Options::LookupInAllReplicas`, `Collection::LookupInReplicaResult`)
* Core update
All tests pass
=> RCBC-443: Support for Subdocument Read from Replica

ext/couchbase.cxx, lib/couchbase/collection.rb, lib/couchbase/collection_options.rb, test/subdoc_test.rb
Any spec-specific errors were ignored which resulted in any error that happens being exposed `PathNotFound` (because of the absence of content)
Add an `error` attribute to the `SubDocumentField` class that stores the Ruby error that is equivalent to the spec-specific error code from the C++ response. This error is raised then `content` or `exists?` for that spec are called
=> RCBC-451 & RCBC-452: Expose any specific lookup_in spec errors

.github/workflows/linters.yml, .rubocop.yml, ext/couchbase.cxx, lib/couchbase/management/bucket_manager.rb, lib/couchbase/management/collection_manager.rb, test/bucket_manager_test.rb, test/collection_manager_test.rb, test/collection_query_index_manager_test.rb, test/test_helper.rb
* Added `CreateCollectionSettings`, `UpdateCollectionSettings`
* Support new signatures for `create_collection` and `drop_collection` to conform to the latest RFC spec (taking `scope_name`, `collection_name`, and a `CreateCollectionSettings` instance (in the case of `create_collection`), instead of a `CollectionSpec` instance)
* Deprecated passing a `CollectionSpec` to `create_collection` and `drop_collection`
* Added `update_collection`
* Support all history retention settings in `BucketSettings`, `CreateCollectionSettings` and `UpdateCollectionSettings`
* Added tests for bucket and collection management
* Added some test helpers for retrying operations
* C++ core update
All tests pass
=> RCBC-453: Support history retention in collection and bucket management

ext/couchbase.cxx, lib/couchbase/collection_options.rb, test/subdoc_test.rb
Bring in changes from couchbaselabs/couchbase-cxx-client#452 and make any necessary wrapper-side changes.
When calling `#content` for an exists spec the result is the same as the result of `#exists`, provided that the subdoc operation was successful or the error was path-not-found (otherwise an error is raised), which is required to be compliant with the RFC. Previously, a PathNotFound error was raised when the path did not exist. This logic is handled by the C++ core
=> RCBC-450: Set value of subdoc exists to true or false if result is success or path-not-found

ext/couchbase.cxx, test/crud_test.rb, test/scan_test.rb, test/search_test.rb, test/subdoc_test.rb
The `retry_reasons` field in the core's error context can be populated even if no retries were attempted. Always include it in the corresponding Ruby error's `context` if it is populated
=> Show retry reasons even if no retries were attempted

lib/couchbase/options.rb
`Utils::Time.extract_expiry_time(expiry)` transforms the expiry to the format expected by the backend. Currently it is called in the constructor, which means that if expiry is set through the setter, it is not being called and the expiry is sent to the backend in the incorrect format resulting in an `ArgumentError`.
 
Call `extract_expiry_time` in the `#to_backend` method instead, so it is always called irrespective of whether expiry was set through the setter or the constructor
This was causing tests in FIT's `ExpiryTest` to fail (the performer was using the setter). Now these tests pass.
=> RCBC-461: Call `extract_expiry_time` in `to_backend` of options instead of constructor

lib/active_support/cache/couchbase_store.rb, test/active_support/behaviors/encoded_key_cache_behavior.rb
* Instead of using `byteslice` use `limit` from active support than ensures that characters are not broken
* Don't force the encoding to ASCII in `normalize_key`
* Add tests to check that truncating keys works as expected
=> Ensure that truncating keys in CouchbaseStore preserves the validity of their encoding

bin/check-clang-static-analyzer, ext/CMakeLists.txt, ext/couchbase.cxx, lib/couchbase/errors.rb, lib/couchbase/protostellar/response_converter/kv.rb, lib/couchbase/protostellar/response_converter/search.rb, test/crud_test.rb
* Add `DocumentNotLocked` error which corresponds to the C++ error code `couchbase::errc::key_value::document_not_locked`
* Necessary changes for core update
=> RCBC-463: Add DocumentNotLocked error & C++ core update

ext/couchbase.cxx, lib/couchbase/management/collection_manager.rb, test/collection_manager_test.rb, test/test_helper.rb
* Change conversions of `max_expiry` from Ruby to C++ and vice versa to take into account that max_expiry is now a signed integer in the collections API
* Raise an `InvalidArgument` error if `max_expiry` is less than `-1`
* Add tests for setting `max_expiry` to `-1` and for invalid values in both `update_collection` and `create_collection`
=> RCBC-468: Support for maxTTL value of -1 for collection 'no expiry'

ext/couchbase.cxx, lib/couchbase/cluster.rb, lib/couchbase/options.rb, lib/couchbase/search_options.rb, test/search_test.rb
* Added the `Cluster#search` method which takes a `Cluster::SearchRequest` object as a parameter
* Added the classes needed to construct vector search queries `Cluster::VectorSearch` and `Cluster::VectorQuery`
* Added some tests to verify the encoding of search requests to the format expected by the C++ backend
* Some general search fixes:
- Removed an incorrect access of the `operator` field in `MatchPhraseQuery` which does not exist
- Fixed the search row locations not being populated correctly in the search result
All tests pass, including all relevant search & vector search tests in FIT
=> RCBC-467: Add support for vector search

Rakefile, ext/couchbase.cxx, test/diagnostics_test.rb
* For the `service_types` option map `:management` and `:eventing` to the corresponding C++ enum values
* In `PingResult`, use the correct symbol for the key of the management service info
=> RCBC-472: Ping management service when specified in options

ext/couchbase.cxx, lib/couchbase/protostellar/scope.rb, test/search_test.rb, test/test_helper.rb
Core update that brings in the following changes from the C++ core:
* [RCBC-473](https://issues.couchbase.com/browse/RCBC-473): FeatureNotAvailable if new search capabilities aren't available
* [RCBC-380](https://issues.couchbase.com/browse/RCBC-380): Create index key encoding
* [RCBC-455](https://issues.couchbase.com/browse/RCBC-455): Update Config When 0xd Response is Received
Added some tests for search `FeatureNotAvailable`. Relevant FIT tests also passing.
=> Update C++ core

.yardopts, lib/couchbase.rb, lib/couchbase/cluster.rb, lib/couchbase/collection.rb, lib/couchbase/errors.rb, lib/couchbase/key_value_scan.rb, lib/couchbase/management/scope_search_index_manager.rb, lib/couchbase/management/search_index_manager.rb, lib/couchbase/protostellar.rb, lib/couchbase/scope.rb, lib/couchbase/search_options.rb
* Added note for stability of `couchbase2://`
* Updated stability for API 3.5 features
* Added a custom stability tag so that it's visible in the API reference.
=> Mark `couchbase2://` scheme as uncommitted & update API 3.5 stability

lib/couchbase/protostellar/bucket.rb, lib/couchbase/protostellar/cluster.rb
The current ping/diagnostics response format does not make sense for `couchbase2`, so it will not be supported for now. This change adds ping/diagnostics methods for `couchbase2` that raise `Error::FeatureNotAvailable`.
=> RCBC-476: FeatureNotAvailable for cb2 ping/diagnostics

lib/couchbase/subdoc.rb
`@expand_macros` should only be set to `true` when the macros are set using the symbols.
From the API documentation:
> When symbol specified and it is matches to known macro, it will be expanded
This fixes the `insertExpandMacroXattrDoNotFlag` failure in FIT.
=> RCBC-482: Only expand MutateIn macros when the relevant symbols are used as values

lib/couchbase/search_options.rb, test/search_test.rb
In 7.6.2, the server will support base64 encoding of vectors in addition to array type "vector". The new encoding type will be accepted via the parameter "vector_base64" in the vector search query.
* Add new overload for the constructor of `VectorQuery` that accepts a string which represents a base64 encoded sequence of little-endian IEEE 754 floats. This is then forwarded as-is in the vector search query using the"vector_base64" parameter.
* Core update to `f72a089` which includes raising `FeatureNotAvailable` in `SearchIndexManager#upsert_index` & `ScopeSearchIndexManager#upsert_index` when upserting indexes with vector definitions to servers that do not support it.
All vector search tests in FIT pass
=> RCBC-489: Support for base64 encoded vector types

lib/couchbase/search_options.rb, test/search_test.rb
From the RFC:
> The current size limit for the vector is 2048 elements, but this will not be enforced on the SDK side. Either vector or vector_base64 must be non-empty though, and if not the SDK will raise InvalidArgument.
=> RCBC-492: InvalidArgument when vector is empty

couchbase.gemspec, ext/0001-fix-build-for-mingw-w64-ucrt-x86_64-toolchain.patch, ext/extconf.rb, ext/rcb_analytics.cxx, ext/rcb_backend.cxx, ext/rcb_backend.hxx, ext/rcb_buckets.cxx, ext/rcb_collections.cxx, ext/rcb_crud.cxx, ext/rcb_diagnostics.cxx, ext/rcb_exceptions.cxx, ext/rcb_exceptions.hxx, ext/rcb_extras.cxx, ext/rcb_multi.cxx, ext/rcb_query.cxx, ext/rcb_range_scan.cxx, ext/rcb_search.cxx, ext/rcb_users.cxx, ext/rcb_utils.cxx, ext/rcb_utils.hxx, ext/rcb_views.cxx, lib/couchbase/errors.rb
https://github.com/couchbase/couchbase-cxx-client/releases/tag/1.0.0
=> Update core to 1.0.0

test/query_index_manager_test.rb, test/utils/consistency_helper.rb
* Add `wait_until_bucket_present_in_indexes` helper
* Append a partial uuid to the bucket name for buckets created in query index tests (avoids the need to ensure the bucket has been dropped after each test)
=> Fix consistency issues with query index tests

ext/rcb_backend.cxx, ext/rcb_crud.cxx, ext/rcb_utils.hxx, lib/couchbase/options.rb, test/crud_test.rb, test/subdoc_test.rb, test/test_helper.rb
Changes:
- Added selected server replica reads for getReplica & lookupInReplica
=> RCBC-487: Implement zone aware replica reads

ext/rcb_crud.cxx
Previously the append and prepend requests in the C++ core did not have a field for CAS. This meant that the relevant option in append/prepend options was being ignored.
* Update C++ core
* Set the CAS option in the C++ wrapper code
Relevant tests in FIT pass.
=> RCBC-513: Forward prepend/append CAS to core

ext/extconf.rb
=> RCBC-515: enforce CMAKE_POLICY_VERSION_MINIMUM to be 3.5 for snappy and cmake 4.x

test/test_helper.rb
simplecov-cobertura v3 doesn't do the `require "simplecov"`. We should now do it ourselves.
=> Test helper: Fix simplecov error

ext/rcb_extras.cxx
Can be used as follows:
```ruby
irb(main):002> Couchbase::Backend::allow_enterprise_analytics 
=> nil
irb(main):003> cluster = Couchbase::Cluster::connect('couchbase://192.168.106.132', 'Administrator', 'password')
=> #<Couchbase::Cluster:0x00000001214146d8>
irb(main):004> cluster.analytics_query('SELECT 1=1')
=> 
#<Couchbase::Cluster::AnalyticsResult:0x0000000121236848
@meta_data=
#<Couchbase::Cluster::AnalyticsMetaData:0x00000001212366b8
@client_context_id="4fabd0-8a39-f149-49e2-86568450b938f7",
@metrics=#<Couchbase::Cluster::AnalyticsMetrics:0x0000000121236488 @elapsed_time=20331816, @error_count=0, @execution_time=2.000000001879481, @processed_objects=0, @result_count=1, @result_size=11, @warning_count=0>,
@request_id="2b0f30b6-0973-4e66-9ff8-16d40454bbc1",
@signature={"*"=>"*"}, …
```
=> RCBC-518: Add way to disable enterprise analytics check programmatically
